

rule get_orf:
	input: "data/Sclerotinia_sclerotiorum.ASM14694v1.dna.toplevel.fa"
	output: "data/Scler_predicted_orfs.fasta"
	shell: "getorf -sequence {input} -outseq {output} -find 3"

rule get_frame_shifts:
	input:
		dna = "data/Scler_predicted_orfs.fasta",
		genome = "data/Sclerotinia_sclerotiorum.ASM14694v1.dna.toplevel.fa"
	output: "data/Scler_300_100.tsv"
	run:
		shell("python3 scripts/Frshft_FINDER.py -input_dna {input.dna} -input_genome {input.genome} -min_orf 300 -interval_length 100 -output {output}")

rule parse_frame_shifts:
	input: "data/Scler_300_100.tsv"
	output: 
		full_tsv = "data/Scler_300_100_prefinal.tsv",
		subset_fasta = "data/Scler_300_100_intersected_prot.fasta",
		subset_tsv = "data/Scler_300_100_intersected_prot.tsv"
	run:
		shell("python3 scripts/parse_fs.py -input {input} -output_full_tsv {output.full_tsv} -output_subset_fasta {output.subset_fasta} -output_subset_tsv {output.subset_tsv}")

rule cdhit_filter:
	input: "data/Scler_300_100_intersected_prot.fasta"
	output: "data/Scler_300_100_cdhit_filtred.fasta"
	shell: "cdhit -i {input} -o {output} -c 0.75 -s 0.75"

rule blastp:
	input: "data/Scler_300_100_cdhit_filtred.fasta"
	output: "data/Scler_300_100_001_blastp_result.tsv"
	shell: "blastp -db data/pdb_db/pdbaa -query {input} -evalue 0.01 -max_target_seqs 1 -outfmt '6 qseqid sseqid evalue qseq sseq' -out {output}"

rule get_id:
	input: "data/Scler_300_100_001_blastp_result.tsv"
	output: "data/Scler_300_100_001_id.txt"
	shell: "cut -d\| -f2 {input} > {output}"

rule efetch_sequences:
	input: "data/Scler_300_100_001_id.txt"
	output: "data/Scler_300_100_001_pdb.fasta"
	shell: "IFS=$'\n'; for i in $(cat {input}); do esearch -db protein -query $i | efetch -format fasta; done > {output}"
