

rule get_orf:
	input: "data/Sclerotinia_sclerotiorum.ASM14694v1.dna.toplevel.fa"
	output: "data/Scler_predicted_orfs.fasta"
	shell: "getorf -sequence {input} -outseq {output} -find 3"

rule get_frame_shifts:
	input:
		dna = "data/Scler_predicted_orfs.fasta",
		genome = "data/Sclerotinia_sclerotiorum.ASM14694v1.dna.toplevel.fa"
	output: "data/Scler_300_100.txt"
	run:
		shell(f"python3 scripts/Frshft_FINDER.py -input_dna {input.dna} -input_genome {input.genome} -min_orf 300 -interval_length 100 -output {output}")

rule get_intersected_prot:
	input: "data/Scler_300_100.txt"
	output: "data/Scler_300_100_intersected_prot.fasta"
	shell: "grep -i 'PROT_INTER' -A1 {input} | grep -v '\-\-' > {output}"

rule cdhit_filter:
	input: "data/Scler_300_100_intersected_prot.fasta"
	output: "data/Scler_300_100_cdhit_filtred.fasta"
	shell: "cdhit -i {input} -o {output} -c 0.75 -s 0.75"


